### ISSUE TITLE
행정구역 데이터 도메인 설계 및 데이터 적재

### ISSUE THREAD

**Issue by parksanghyeop** [jjinppang/jjinppang#15]
### ⏰ Estimated Time

4

### 🛠️ Description

법정동 기준으로 제공되는 csv 파일 가공해서 db에 저장하고 api 구현

### ✅ Tasks

- [x] 행정구역 데이터 csv파일 파싱
- [x] 행정구역 중심좌표 지정
- [x] 행정구역 조회 API
