### ISSUE TITLE
소셜 로그인 사용자 인증 구현

### ISSUE THREAD

**Issue by parksanghyeop** [jjinppang/jjinppang#2]
### ⏰ Estimated Time

3

### 🛠️ Description

Spring Security를 사용한 JWT 기반 인증 로직을 구현합니다

### ✅ Tasks

- [x] Spring Security 인증 로직 JWT기반으로 변경
- [x] 인증 객체 클래스 작성
- [x] 회원가입 API 구현
