### ISSUE TITLE
실거래 내역 수집 & 저장 코드 작성

### ISSUE THREAD

**Issue by parksanghyeop** [jjinppang/jjinppang#7]
### ⏰ Estimated Time

8

### 🛠️ Description

공공데이터포털에서 제공하는 API로 데이터 요청하여 실거래 내역 DB에 저장

### ✅ Tasks

- [ ] API 호출 코드 작성
- [ ] DB 저장 코드 작성
- [ ] 스케줄링 적용
- [ ] 스케줄링을 통한 반복 작업시 통계정보 갱신 코드 작성
